#!/usr/bin/env bash
# S05 Human Verification Checklist — Settings & Preferences
# Run this script for step-by-step manual verification instructions.

set -euo pipefail

echo "═══════════════════════════════════════════════════════"
echo "  S05: Settings & Preferences — Human Verification"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "1. BUILD & LAUNCH"
echo "   swift build && .build/debug/KimchiCompanion"
echo "   (or open in Xcode and run)"
echo ""
echo "2. SETTINGS SECTION VISIBLE"
echo "   • Click the menu bar icon to open the popover"
echo "   • Scroll down past 'Open Dashboard' link"
echo "   • Verify 'Settings' header is visible"
echo "   • Verify Refresh picker, Display picker, Launch at Login toggle,"
echo "     Change API Key button, and Remove API Key button are all present"
echo ""
echo "3. DISPLAY MODE"
echo "   • Change Display to 'Icon Only' → menu bar should show only the icon, no text"
echo "   • Change Display to 'Icon + Cost' → menu bar should show icon + dollar amount"
echo "   • Change Display to 'Icon + Tokens' → menu bar should show icon + token count"
echo ""
echo "4. REFRESH INTERVAL PERSISTENCE"
echo "   • Change Refresh to '1 min'"
echo "   • Close the popover"
echo "   • Run: defaults read com.kimchicompanion.refreshInterval"
echo "   • Verify output is 60"
echo "   • Change to '5 min' and verify output is 300"
echo ""
echo "5. DISPLAY MODE PERSISTENCE"
echo "   • Change Display to 'Icon + Tokens'"
echo "   • Run: defaults read com.kimchicompanion.displayMode"
echo "   • Verify output is 'iconAndTokens'"
echo ""
echo "6. LAUNCH AT LOGIN"
echo "   • Toggle 'Launch at Login' on"
echo "   • NOTE: Only works in a proper .app bundle (not debug builds)"
echo "   • In debug builds, check console for LaunchAtLogin log messages"
echo ""
echo "7. REMOVE API KEY"
echo "   • Click 'Remove API Key'"
echo "   • Verify confirmation alert appears"
echo "   • Click 'Remove'"
echo "   • Verify app returns to setup/API key entry view"
echo "   • Verify no data is shown (cached data cleared)"
echo ""
echo "8. RESTART PERSISTENCE"
echo "   • Set some non-default preferences (e.g., 1 min refresh, Icon Only)"
echo "   • Quit and relaunch the app"
echo "   • Open popover → Settings"
echo "   • Verify preferences were preserved across restart"
echo ""
echo "═══════════════════════════════════════════════════════"
echo "  All checks passed? S05 is verified! ✅"
echo "═══════════════════════════════════════════════════════"
